# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=26.3
neo_version=26.3.0.1-beta
mod_group=com.sakuraryoko
mod_id=unplugged_afk
mod_archive_name=unplugged_afk

#Publishing
mod_name=unplugged_afk
curseforge_id=1690101
modrinth_id=Xor3WVYR

# Version
version=0.2.5.1

# Dependencies
opencsv_version=5.12.0

# https://github.com/Fallen-Breath/conditional-mixin
conditionalmixin_version=0.6.4